id: I46CBB649
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:50:21.740657
last_modified: 2023-02-09 14:50:21.740776
source_metadata:
  title: 'PP: Ratnaguṇasaṃcayagāthā'
  language: sa
bases:
  38DD:
    base_file: 38DD.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
